"""Generate the complete runtime ID table and human-readable converted animal catalog."""
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = Path(sys.argv[1]).resolve() if len(sys.argv)>1 else ROOT / 'assets/animals'


def main():
    recipe = json.loads((ASSETS / 'animals.source.json').read_text())
    manifest = json.loads((ASSETS / 'animals.manifest.json').read_text())
    assert not manifest.get('failures'), manifest.get('failures')
    assert {e['id'] for e in recipe['animals']} == set(manifest['animals'])
    rows = ['// Generated by scripts/catalog_animals.py; original four IDs stay stable.']
    table = ['# Converted animal catalog', '', '| ID | Source prefab | Bones | Clips |', '| --- | --- | ---: | ---: |']
    for entry in recipe['animals']:
        name = entry['id']
        asset = manifest['animals'][name]
        bounds = asset['bounds_blender']
        radius = max(.12, math.hypot(max(abs(b[0]) for b in bounds), max(abs(b[1]) for b in bounds)))
        speed = max(.2, min(1.5, radius*.75))
        radius, speed = {'horse': (1.6, 1.2), 'hen': (.35, .55), 'cow': (1.5, .8), 'cat': (.4, .65)}.get(name, (radius, speed))
        symbol = ''.join(word.capitalize() for word in name.split('_'))
        rows.append(f'DW_ANIMAL({symbol}, "{name}", {radius:.4f}f, {speed:.4f}f)')
        table.append(f'| `{name}` | {Path(entry["prefab"]).stem} | {asset["bones"]} | {len(asset["clips"])} |')
    (ROOT / 'src/world/AnimalCatalog.inc').write_text('\n'.join(rows)+'\n')
    (ASSETS / 'CATALOG.md').write_text('\n'.join(table)+'\n')
    print(f'Catalog: {len(recipe["animals"])} variants, {recipe["family_count"]} folders, '
          f'{sum(len(a["clips"]) for a in manifest["animals"].values())} exported clips')


if __name__ == '__main__':
    main()
